server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/agents
    username: agents
    password: agents
  liquibase:
    change-log: classpath:db/changelog/master.xml
  kafka:
    bootstrap-servers: localhost:9092
  application:
    name: scraper-service

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  metrics:
    tags:
      application: ${spring.application.name}
