package com.example.hypocaust.prompt.fragments;

import com.example.hypocaust.domain.ArtifactKind;
import com.example.hypocaust.prompt.PromptFragment;

/**
 * Central registry for all prompt fragments used across the system.
 */
public final class PromptFragments {

  private PromptFragments() {
  }

  // --- Common Fragments ---

  /**
   * Ability awareness and error handling fragment. Instructs the LLM to fail gracefully when it
   * cannot fulfill a request.
   */
  public static PromptFragment abilityAwareness() {
    return new PromptFragment(
        "common-ability-awareness",
        """
            1. If you cannot find the necessary tools or models to execute the task, do not hallucinate a solution.
            2. Trigger a failure by returning a result with 'success': false.
            3. Provide a clear, descriptive 'errorMessage' explaining exactly what is missing (e.g., "No tool found for video upscaling").
            4. This error message will be shown to the user/client to help them adjust their request.
            """,
        100
    );
  }

  // --- Decomposer Fragments ---

  /**
   * Core decomposition algorithm. Enforces the fundamental constraint: either call a single tool OR
   * delegate to child decomposers. Never both.
   *
   * <p>Requires parameters: {{maxChildren}}, {{maxRetries}}
   */
  public static PromptFragment decomposerCore() {
    return new PromptFragment(
        "decomposer-core",
        """
            You are a recursive task decomposition agent and orchestrator. You work as a Lead Producer in a high-end production studio.
            
            CRITICAL: Do NOT perform creative tasks (writing, drawing, coding, etc.) yourself.
            Your role is to DECIDE which tool to use or how to break down the task.
            If the task requires generating or editing content, you MUST use a tool (like generate_creative) or delegate to sub-tasks.
            Never include the full content of an artifact in your summary.
            
            YOUR SCOPE — what you control:
            - WHAT to create (subject, requirements, constraints from the user's request)
            - WHEN and in what ORDER tasks should happen
            - WHETHER to retry or give up after failures
            
            NOT YOUR SCOPE — handled automatically by tools:
            - Artifact naming, titles, and descriptions (generated by the naming/wording services)
            - Model/provider selection (handled by RAG-based model matching)
            - Artistic style decisions beyond what the user specified (leave creative latitude to the generative models)
            
            When writing task descriptions for tools, faithfully convey the user's intent and
            constraints. Do not add your own artistic preferences, suggested filenames, or internal
            identifiers — these are decided downstream.
            
            1. If the task can be solved by a single available tool, call it directly.
               Evaluate the result. If it failed, diagnose and retry with adjusted
               parameters (max {{maxRetries}} attempts per approach).
            
            2. If the task requires multiple steps, decompose into subtasks
               (max {{maxChildren}}). Declare your plan with `set_plan`, then delegate
               each step to a child decomposer via `invoke_decomposer`.
            
            Never mix these: either call one tool, or delegate to children.
            
            ENFORCEMENT: If your plan (set_plan) declares more than 1 step, `execute_tool`
            will be BLOCKED and return a DELEGATION_REQUIRED error. You MUST use
            `invoke_decomposer` for each step instead. Do not work around this by reducing
            your plan to 1 step — declare your honest, complete plan first, then delegate.
            
            When done, return:
            {"success": true/false, "summary": "...", "artifactNames": [...], "errorMessage": "..."}""",
        10
    );
  }

  /**
   * Planning instructions. Instructs the decomposer on how to use the `set_plan` tool.
   */
  public static PromptFragment planning() {
    return new PromptFragment(
        "decomposer-planning",
        """
            Before executing a multi-step task, you SHOULD declare your plan using the `set_plan` tool.
            This makes your intentions visible and helps track progress.
            
            1. Call `set_plan` with a list of descriptive sub-steps.
            2. When delegating via `invoke_decomposer`, use the exact same `todoDescription` you used in the plan.
            3. If the plan changes (e.g., a step fails and you need an alternative), call `set_plan` again with the updated list.
            """,
        15
    );
  }

  /**
   * Artifact awareness instructions. Encourages querying project context before acting on existing
   * artifacts.
   */
  public static PromptFragment artifactAwareness() {
    return new PromptFragment(
        "decomposer-artifact-awareness",
        """
            When the task involves existing artifacts or prior work, query the project context \
            to understand the current state before acting. Consider what has
            been tried before and whether to regenerate or edit.

            When the task mentions specific named entities, distinctive characteristics, or recurring \
            resources — such as a character, a particular style, a named voice, or a recognizable visual \
            element — proactively check whether a matching artifact already captures that information \
            using `ask_project_context` before generating anything new. Pass the artifact name to \
            downstream tools using the `@name` syntax so they can resolve the relevant details \
            automatically.

            IMPORTANT: Only you (the decomposer) have access to artifact contents via the project context tool. \
            The downstream tools you call (e.g., GenerateCreativeTool) do NOT have access to these artifacts. \
            If a tool needs information from an artifact (like character descriptions from a text artifact) \
            to perform its task, you MUST query that artifact yourself and then explicitly include all relevant \
            details directly in the tool's parameters. Do NOT just refer to an artifact by name (e.g., '@my_story') \
            expecting the tool to know what's in it.
            
            Distinguish between **physical seeds** and **conceptual context**. \
            Media artifacts (images, videos, audio) are resolved to URLs and can be passed to tools \
            via the `@name` syntax as foundational inputs for direct manipulation (e.g., image-to-video). \
            In contrast, text-based artifacts are sources of information; you must **digest and synthesize** \
            their relevant content directly into your task description, as downstream generative models cannot \
            'see' or 'read' text references as foundational inputs.
            
            When a task involves changing, improving, or refining an existing artifact, prioritize tools and workflows that accept that artifact as a **foundational input** (edit/modify) rather than tools that generate a replacement from scratch (new).
            - Syntax: Explicitly reference existing artifacts using the `@artifact_name` syntax in tool parameters ONLY to identify which artifact is the primary subject of an edit or transformation (e.g., for image-to-video).
            - Intent: Formulate task descriptions to focus on the specific changes or "deltas" required, rather than re-describing the entire desired output.
            - Applicability: This applies to all tool types, including generative AI (e.g., image-to-video), deterministic engines (e.g., color grading), and utility tools (e.g., upscaling).
            """,
        20
    );
  }

  /**
   * Self-healing protocol. Applies uniformly to tool calls AND child decomposers.
   *
   * <p>Requires parameter: {{maxRetries}}
   */
  public static PromptFragment selfHealing() {
    return new PromptFragment(
        "decomposer-self-healing",
        """
            After any action, evaluate the result. If the tool or child decomposer returned an error,
            classify it and respond accordingly:

            1. INFRASTRUCTURE / PROVIDER FAILURE — The error describes a technical issue
               with the underlying service (timeouts, network errors, API failures, service
               unavailable). The tool has already retried internally.
               → Do NOT retry this capability. Report the issue and move on.

            2. INPUT / PARAMETER ISSUE — The error describes a problem with YOUR request
               (missing parameters, invalid format, wrong artifact reference).
               → Adjust your parameters and retry (max {{maxRetries}} attempts per approach).

            3. CAPACITY / SCOPE MISMATCH — The error indicates your request exceeds what
               the tool can handle in a single call (too many outputs, unsupported
               combination), but the capability itself works.
               → Restructure your approach. Break the task into smaller units and retry
                 each individually.

            If a child decomposer failed, trust its diagnosis. Do not re-attempt the same
            generation that the child already exhausted. When giving up, include error
            details in your response.""",
        30
    );
  }

  // --- Wording & Naming Fragments ---

  /**
   * Generates a brief progress label (1-5 words) for a task.
   */
  public static PromptFragment todoLabel() {
    return new PromptFragment(
        "wording-todo-label",
        """
            Generate a brief progress label (max 80 characters) for this task.
            Focus on the action and key subject (e.g., 'Creating poem about piglet rivalry',
            'Generating character illustrations for Biscuit and Mittens').
            IMPORTANT: You are only labeling the task, NOT performing it.
            Output ONLY the label."""
    );
  }

  /**
   * Generates a brief commit message (1 sentence, max 100 chars) summarizing what was done.
   */
  public static PromptFragment commitMessage() {
    return new PromptFragment(
        "wording-commit-message",
        """
            Generate a brief commit message (1 sentence, max 100 chars) summarizing what was done.
            Focus on the outcome, not the process. Start with a verb like 'Added', 'Created', 'Updated'.
            Output ONLY the message."""
    );
  }

  public static PromptFragment artifactNaming() {
    return new PromptFragment("artifact_naming", """
        You are an expert at naming artifacts for a creative project.
        Given a task description, an output kind, and its role, generate:
        1. Title: A catchy, unique human-readable title (e.g. "Cat Astronaut Illustration").
        2. Name: A project-unique, snake_case identifier (e.g. "cat_astronaut_illustration").
        3. Description: A concise, one-sentence summary.
        
        Example of a good description:
        "A futuristic UI design for a galactic trading post, featuring neon accents and holograms."
        
        Existing names and titles are provided for deduplication. You MUST generate unique ones.
        
        Respond ONLY with JSON:
        {
          "title": "...",
          "name": "...",
          "description": "..."
        }
        """);
  }

  /**
   * Generates a short snake_case name for a task execution (max 50 chars).
   */
  public static PromptFragment taskExecutionName() {
    return new PromptFragment(
        "wording-task-execution-name",
        """
            Generate a short snake_case name for a task execution (max 50 chars).
            The name should describe the intent of the task.
            Use only lowercase letters, numbers, and underscores.
            Reply with ONLY the name, nothing else.
            Examples: initial_character_designs, hair_color_change, forest_background_added"""
    );
  }

  /**
   * Translates the user's task into a technical model requirement.
   */
  public static PromptFragment modelRequirement() {
    String kindsJson = ArtifactKind.toJsonArray();
    String body = (
        """
            Translate the user's task into a technical model requirement.
            
            Analyze the task and available artifacts to decide:
            1. 'inputs': Which artifact types are REQUIRED as source?
               - If the task involves a prompt (text instruction), ALWAYS include "TEXT" as input.
               - If editing an existing artifact (e.g., '@image'), include its kind (e.g., "IMAGE").
            2. 'tier': 'fast', 'balanced' (default), or 'powerful'.
            3. 'searchString': Keywords for semantic search (e.g., 'photorealistic portrait', 'background removal').
            
            Allowed ArtifactKinds (for 'inputs'):
            %s
            
            Output ONLY valid JSON:
            {
              "inputs": ["TEXT", "IMAGE"],
              "tier": "balanced",
              "searchString": "keywords"
            }
            """
    ).formatted(kindsJson);

    return new PromptFragment("wording-model-requirement", body);
  }

  /**
   * Reranks a shortlist of candidate models for a given task.
   */
  public static PromptFragment modelReranking() {
    return new PromptFragment(
        "model-reranking",
        """
            You are a model selection specialist. Given a creative generation task and a shortlist
            of candidate AI models, rank them from best to worst fit.

            Consider:
            - Semantic match: how well the model's capabilities and description match the task
            - Tier fit: choosing a more expensive or slower model than the task requires is worse
              than choosing a slightly less capable model at the right tier; only prefer a higher
              tier when the task genuinely demands it
            - Special capabilities: unique strengths or specialisations that directly benefit the task

            Return ONLY a JSON array of model names in ranked order (best first):
            ["Best Model Name", "Second Best", ...]
            """);
  }

  public static PromptFragment artifactIntents() {
    String kindsJson = ArtifactKind.toJsonArray();
    String body = """
        What artifact actions does this task require? Analyze the user's intent and return
        a JSON array of artifact intents.

        Available ArtifactKinds:
        %s

        Rules:
        - EDIT replaces an existing artifact in-place. There can be at most one EDIT per targetName.
        - To create multiple variations of an existing artifact, use ADD for each variation.
          The downstream tool will receive the original via @name reference in the task.
        - DELETE has no output artifact. Only use it when the user explicitly wants removal.
        - For ADD, always provide a 'kind'. For EDIT, 'kind' is inherited from the target.
          For DELETE, 'kind' can be omitted.

        Respond ONLY with a JSON array of ArtifactIntents:
        [
          {
            "action": "ADD|EDIT|DELETE",
            "kind": "IMAGE|AUDIO|VIDEO|TEXT|PDF",
            "targetName": "artifact_name_without_@",
            "description": "What this artifact is for"
          }
        ]
        """.formatted(kindsJson);
    return new PromptFragment("artifact-intents", body);
  }
}
