spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.the_machine: DEBUG
    org.springframework.test: DEBUG