management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.the_machine: DEBUG
    org.springframework.web: DEBUG