package com.example.hypocaust.domain;

import com.fasterxml.jackson.databind.JsonNode;
import lombok.Builder;
import lombok.NonNull;

/**
 * A draft version of an artifact, used when requesting to add an artifact to the context. It does
 * not have a name yet, as the name is generated by the system.
 */
@Builder
public record ArtifactDraft(
    @NonNull ArtifactKind kind,
    @NonNull String title,
    @NonNull String description,
    @NonNull ArtifactStatus status,
    String url,
    JsonNode inlineContent,
    JsonNode metadata
) {

}
