apiVersion: v1
kind: Pod
metadata:
  name: hypocaust-ffmpeg
spec:
  volumes:
    - name: ffmpeg_data
      hostPath:
        path: ${HOSTPATH}/podman/volumes/ffmpeg
  containers:
    - name: ffmpeg
      image: docker.io/rendiffdev/ffmpeg-api:latest
      envFrom:
        - configMapRef:
            name: hypocaust-dev
      volumeMounts:
        - mountPath: /data:Z
          name: ffmpeg_data
          readOnly: false
      ports:
        - containerPort: 8000
          hostPort: 8100
          protocol: TCP
