apiVersion: v1
kind: Pod
metadata:
  name: the_machine-postgres
spec:
  volumes:
    - name: postgres_data
      hostPath:
        path: ${HOSTPATH}/podman/volumes/postgres
  containers:
    - name: postgres
      image: docker.io/library/postgres:17.2
      envFrom:
        - configMapRef:
            name: the_machine-dev
      volumeMounts:
        - mountPath: /var/lib/postgresql/data:Z
          name: postgres_data
          readOnly: false
      ports:
        - containerPort: 5432
          hostPort: 7888
          protocol: TCP
    - name: pgadmin
      image: docker.io/dpage/pgadmin4:2024-12-09-2
      envFrom:
        - configMapRef:
            name: the_machine-dev
      ports:
        - containerPort: 80
          hostPort: 7889
          protocol: TCP
